name: Build & Upload to Loadly

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Build .ipa (tuỳ project bạn thay lệnh build)
      - name: Build iOS IPA
        run: |
          xcodebuild -workspace MyApp.xcworkspace \
                     -scheme MyApp \
                     -archivePath ${{ github.workspace }}/MyApp.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/MyApp.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ${{ github.workspace }}/build

      # 3. Lấy appKey & buildKey (nếu bạn muốn tự động)
      - name: Fetch Loadly appKey
        env:
          LOADLY_API_KEY: ${{ secrets.LOADLY_API_KEY }}
        run: |
          resp=$(curl -s -X POST https://api.loadly.io/apiv2/app/listMy \
            -d "_api_key=$LOADLY_API_KEY")
          echo "APP_KEY=$(echo $resp | jq -r '.data[0].appKey')" >> $GITHUB_ENV

      # 4. Upload file lên Loadly
      - name: Upload to Loadly.io
        env:
          LOADLY_API_KEY: ${{ secrets.LOADLY_API_KEY }}
          APP_KEY: ${{ env.APP_KEY }}
        run: |
          curl -X POST https://api.loadly.io/apiv2/app/upload \
            -F "_api_key=$LOADLY_API_KEY" \
            -F "appKey=$APP_KEY" \
            -F "file=@${{ github.workspace }}/build/MyApp.ipa"
