name: Upload IPA to Loadly

# Bạn có thể trigger tự động trên push tag, hoặc bằng tay qua workflow_dispatch
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload IPA to Loadly
        run: |
          curl -X POST https://api.loadly.io/apiv2/app/upload \
            -F "_api_key=${{ secrets.LOADLY_API_KEY }}" \
            -F "appKey=${{ secrets.LOADLY_APP_KEY }}" \
            -F "file=@${{ github.workspace }}/releases/MyApp.ipa"
